pipeline {
    agent { docker 'maven:3-alpine' }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package docker:build'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker stop eurekasvr'
                sh 'docker run -d --rm -p 8761:8761 --name eurekasvr xuerge/eurekasvr:1.0'
            }
        }
    }
}